global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "currency-rate-provider"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          service: "currency-rate-provider"

  - job_name: "rate-printer"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          service: "rate-printer"
