server.port=8081
spring.application.name=rate-printer
app.version=1.0.0
rate-provider.url=http://localhost:8080

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
